apiVersion: v1
kind: Service
metadata:
  name: mathswallah-svc
  namespace: mathswallah
spec:
  type: NodePort
  selector:
    app: mathswallah
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
